server:
  port: 9004
spring:
  application:
    name: csdn-article
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.198.128:3306/tensquare_article?characterEncoding=utf-8
    username: root
    password: root
  data:
    mongodb:
      database: commentdb
      host: 192.168.198.128
      port: 27017
  redis:
    host: 192.168.198.128
    port: 6379
  rabbitmq:
    host: 192.168.198.128

# Mybatis-Plus 配置
mybatis-plus:
  typeAliasesPackage: com.tensquare.article.pojo
  global-config:
    id-type: 1 #0:数据库ID自增 1:用户输入id
    db-column-underline: false
    refresh-mapper: true
    configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启延时加载，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
    instance:
      prefer-ip-address: true